name: Latest YouTube Videos
on:
  schedule:
    - cron: '15 10 * * *' # Runs daily
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYcGVOtMxDEnXQs5AMjZFYA"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: |
            <h3 align="center">🎬 Latest Videos</h3>
          
            <div align="center" style="display: flex; flex-direction: column; gap: 20px;">
            
            <div style="background: rgba(255, 255, 255, 0.15); border-radius: 15px; padding: 15px; max-width: 500px; text-align: center; box-shadow: 5px 5px 20px rgba(0, 0, 0, 0.3); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.3); transition: transform 0.3s ease-in-out;">
            <a href="$url"><img width="100%" src="https://images.weserv.nl/?url=i.ytimg.com/vi/$videoId/hqdefault.jpg" style="border-radius: 10px;"></a>
            <br><a href="$url" style="font-size: 18px; font-weight: bold; text-decoration: none; color: #fff;">$title</a><br>
            <i style="color: #ddd;">$date</i>
            </div>
          
            </div>
          committer_email: "textzip@gmail.com"
