name: Latest YouTube Videos
on:
  schedule:
    - cron: '15 10 * * *' # Runs daily
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYcGVOtMxDEnXQs5AMjZFYA"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: |
            <h3 align="center">🎬 Latest Videos</h3>
            <div align="center">
            <table>
            <tr>
            
            $newline<td>
            <div style="border: 2px solid #444; border-radius: 10px; padding: 10px; width: 280px; text-align: center; box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);">
            <a href="$url"><img width="260px" src="https://images.weserv.nl/?url=i.ytimg.com/vi/$videoId/hqdefault.jpg" style="border-radius: 10px;"></a>
            <br><a href="$url"><b>$title</b></a><br>
            <i>$date</i>
            </div>
            </td>
          
            $newline{{#if hasMore}}
            
            $newline<td>
            <div style="border: 2px solid #444; border-radius: 10px; padding: 10px; width: 280px; text-align: center; box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);">
            <a href="$url"><img width="260px" src="https://images.weserv.nl/?url=i.ytimg.com/vi/$videoId/hqdefault.jpg" style="border-radius: 10px;"></a>
            <br><a href="$url"><b>$title</b></a><br>
            <i>$date</i>
            </div>
            </td>
          
            $newline{{/if}}
          
            $newline{{#if isLastInRow}}
            </tr><tr>
            {{/if}}
          
            </table>
            </div>
          committer_email: "textzip@gmail.com"
